version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - '/node_modules'

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    # volumes:
    #   - $PWD/redis-data:/var/lib/redis
    #   - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
